language: rust
rust:
  - stable
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
cache: cargo
sudo: false
dist: trusty
addons:
  apt:
    sources:
    - sourceline: 'ppa:chris-lea/libsodium'
    - sourceline: 'ppa:giskou/librocksdb'
    packages:
    - libsodium-dev
    - libsnappy-dev
    - librocksdb
    - jq
env:
  global:
  - NIGHTLY_RUST=nightly-2017-10-19
  - CLIPPY_VERS=0.0.166
  - RUSTFMT_VERS=0.9.0
  - ROCKSDB_LIB_DIR=/usr/lib/x86_64-linux-gnu
  - SNAPPY_LIB_DIR=/usr/lib/x86_64-linux-gnu
  - secure: K5mZuLSnf9fYdGV0LjiMHKExcO+E9wi/LjxHZKKjaj+/pghYo2fz1/YBxNKAVl7DLWW1iLDEIRKj6DkciBVNnzUbpvLnuzizitdUeVKzSBVxDpOIB6h94K1QR2MUSUx7Xi84s93xBRpJljXo8pXFPLvhPKjHLv0fAHGooq2KwPPfCgWH5ofTRKNkVnyR8tscfGwh1AiQd8+OcJow3lnfXMnuex0kaAX6ziFQfg79nUojpv5DKmMBHh88ZH3TIHW2d4aa2Z/4ZoGfS3rP/LR70yPUZKfGlRmHo0fImam/fRouQJX0Yde7+dtt3sF34ZGwZOXHj5X/OUWPKkCvk6xuwb1qOugpFnr5N31ZoqYGCV8TfvtX+bCOsoUJU0tY7Zj4jRugG9c3IB+98Pr/ECH2Lp2G1ezYniDjzbV8k3rwMR5spMhkdEJdjmhrBuBKNiC+yJOyo5SSonDcf8y7w9DcwtvWUi2AMcmsp4SDSccFP9amOOvT/AW1wor+QEl+PdM14DB7IIVs2wdh23KrVKsZZcq0PR459Tb7YMeZJWslcZp/KGbamHnOs0fSt5ek5ey/zv2G4CdxEvG2naQJEqI7MtvDtHo0ttyrDDG3vb8cCJbEvi3CYI8aktIat4pSd9cNP8snE7eIaWcHUKYJDuPujQwBuHdNdqVWlAqwRnut4NQ=
before_install:
- rustfmt --version | grep $RUSTFMT_VERS || cargo install rustfmt --force --vers $RUSTFMT_VERS
- rustup toolchain install $NIGHTLY_RUST
- cargo +$NIGHTLY_RUST clippy --version | grep $CLIPPY_VERS || cargo +$NIGHTLY_RUST
  install clippy --force --vers $CLIPPY_VERS
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libsodium rocksdb jq; fi
script:
- cargo fmt -- --write-mode=diff
- cargo +$NIGHTLY_RUST clippy -- -D warnings
- cargo test
- cd examples && bash test.sh
